version: '3.8'

services:

  routeros:
    build: .docker/routeros/.
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "12222:22"
      - "12223:23"
      - "18728:8728"
      - "18729:8729"
      - "18291:8291"
    volumes: 
      - ./scripts:/opt/scripts  